kind: pipeline
type: docker
name: create-preview

# test commit 3
steps:
- name: test
  image: alpine
  commands:
  - echo "Create preview environment"
trigger:
  ref:
  - refs/pull/**
  event:
  - create
